import type { ConnectorRecord, FrictionEvent } from "@/lib/types/runtime";
import { evaluateEvent } from "@/lib/friction/evaluator";
import { createId, createTraceEntry, nowIso } from "@/lib/runtime/utils";

export const BUILTIN_CONNECTORS: ConnectorRecord[] = [
  {
    id: "builtin-slack",
    sourceType: "builtin",
    name: "Slack Ops",
    category: "communications",
    protocol: "demo-adapter",
    transport: "stream",
    trustMode: "coach",
    description: "Slack-like communication feed with heated thread interception.",
    snapshot: "Watching live team conversations for heat and repair moments.",
    supports: ["heat scoring", "cooling drawer", "apology fast lane"],
    connected: true,
    health: "live",
    owner: "Operations",
    lastSync: nowIso(),
    latencyMs: 180,
    reliability: 99,
    volume: "high",
    auth: "workspace demo",
    history: [],
  },
  {
    id: "builtin-gmail",
    sourceType: "builtin",
    name: "Gmail Risk",
    category: "finance",
    protocol: "demo-adapter",
    transport: "polling",
    trustMode: "review",
    description: "Finance inbox with spoof, urgency, and transfer-risk detection.",
    snapshot: "Watching invoice requests, executive spoofing, and payment urgency.",
    supports: ["invoice screening", "recipient trust check", "wire transfer hold"],
    connected: true,
    health: "live",
    owner: "Finance",
    lastSync: nowIso(),
    latencyMs: 420,
    reliability: 97,
    volume: "medium",
    auth: "workspace demo",
    history: [],
  },
  {
    id: "builtin-notion",
    sourceType: "builtin",
    name: "Notion Studio",
    category: "creative",
    protocol: "demo-adapter",
    transport: "snapshot",
    trustMode: "interrogate",
    description: "Creative workspace that catches thin prompts and generic draft requests.",
    snapshot: "Watching briefs for missing audience, tension, and angle.",
    supports: ["brief interrogation", "contrast drafts", "revision trace"],
    connected: true,
    health: "warm",
    owner: "Brand",
    lastSync: nowIso(),
    latencyMs: 150,
    reliability: 95,
    volume: "medium",
    auth: "workspace demo",
    history: [],
  },
  {
    id: "builtin-calendar",
    sourceType: "builtin",
    name: "Calendar Flow",
    category: "habit",
    protocol: "demo-adapter",
    transport: "stream",
    trustMode: "prescribe",
    description: "Schedule and behavior pattern source for drift and overload.",
    snapshot: "Watching meeting density, lost focus blocks, and fatigue patterns.",
    supports: ["focus diagnostics", "burnout scans", "lab prescriptions"],
    connected: true,
    health: "live",
    owner: "Operations",
    lastSync: nowIso(),
    latencyMs: 260,
    reliability: 98,
    volume: "medium",
    auth: "workspace demo",
    history: [],
  },
  {
    id: "builtin-browser",
    sourceType: "builtin",
    name: "Browser Pulse",
    category: "habit",
    protocol: "demo-adapter",
    transport: "local-bridge",
    trustMode: "observe",
    description: "Tab drift and shopping-loop detector.",
    snapshot: "Can surface autopilot behavior when enabled.",
    supports: ["tab drift", "doomscroll detection", "shopping impulse patterns"],
    connected: false,
    health: "offline",
    owner: "Local agent",
    lastSync: null,
    latencyMs: 90,
    reliability: 88,
    volume: "high",
    auth: "desktop bridge",
    history: [],
  },
];

const TEMPLATE_LIBRARY: Record<string, Omit<FrictionEvent, "id" | "sourceId" | "sourceType" | "receivedAt" | "status" | "evaluation" | "trace">[]> = {
  "builtin-slack": [
    {
      title: "Escalating deployment thread",
      summary: "A public release thread is getting personal and the replies are hardening.",
      preview: "Two replies contain blame framing and direct pressure to answer now.",
      domain: "communications",
      actor: "Ops lead",
      surface: "#release-war-room",
      urgency: 74,
      sentiment: 82,
      tags: ["heat", "public-channel", "manager-visible"],
    },
    {
      title: "Apology draft ready",
      summary: "A teammate rewrote a defensive message into an accountable apology.",
      preview: "The draft now contains ownership language and a repair ask.",
      domain: "communications",
      actor: "Engineering manager",
      surface: "direct message",
      urgency: 20,
      sentiment: 12,
      tags: ["apology", "repair"],
    },
  ],
  "builtin-gmail": [
    {
      title: "Urgent invoice wire request",
      summary: "An external sender requests same-day payment to a new beneficiary.",
      preview: "Recipient details changed and the sender is applying urgency pressure.",
      domain: "finance",
      actor: "External vendor",
      surface: "finance inbox",
      urgency: 90,
      sentiment: 12,
      amount: 3200,
      tags: ["invoice", "new-recipient", "urgent"],
    },
    {
      title: "Executive spoof request",
      summary: "An executive lookalike email asks for a quick gift-card purchase.",
      preview: "The message tries to bypass normal controls and create false urgency.",
      domain: "finance",
      actor: "Spoofed executive",
      surface: "executive relay",
      urgency: 94,
      sentiment: 15,
      amount: 900,
      tags: ["spoof-risk", "urgent", "gift-card"],
    },
  ],
  "builtin-notion": [
    {
      title: "One-line launch prompt",
      summary: "A brief asks for polished copy without audience, tension, or honest angle.",
      preview: "The request is likely to produce instant slop without interrogation.",
      domain: "creative",
      actor: "Founder note",
      surface: "launch brief",
      urgency: 44,
      sentiment: 18,
      tags: ["slop-risk", "launch"],
    },
    {
      title: "Board memo for contrast drafting",
      summary: "A strategy note has enough raw material for multiple directions, but no contrast yet.",
      preview: "The system should force opposing drafts before polishing anything.",
      domain: "creative",
      actor: "CEO memo",
      surface: "strategy page",
      urgency: 36,
      sentiment: 14,
      tags: ["contrast", "strategy"],
    },
  ],
  "builtin-calendar": [
    {
      title: "Focus block collapse",
      summary: "Meeting density has erased the remaining focus windows for the day.",
      preview: "The operator is drifting toward reactive work and late-day fatigue.",
      domain: "habit",
      actor: "Calendar graph",
      surface: "afternoon schedule",
      urgency: 58,
      sentiment: 42,
      tags: ["fatigue", "meetings", "focus-loss"],
    },
    {
      title: "Late-night purchase window",
      summary: "Low-energy hours and repeated shopping loops point to autopilot risk.",
      preview: "The user is more likely to optimize for convenience than judgment.",
      domain: "habit",
      actor: "Behavior model",
      surface: "night routine",
      urgency: 64,
      sentiment: 46,
      tags: ["autopilot", "late-night"],
    },
  ],
  "builtin-browser": [
    {
      title: "Tab drift surge",
      summary: "Rapid tab switching suggests a drift pattern rather than focused work.",
      preview: "The session is bouncing between social, shopping, and news tabs.",
      domain: "habit",
      actor: "Local bridge",
      surface: "browser session",
      urgency: 62,
      sentiment: 44,
      tags: ["autopilot", "doomscroll"],
    },
  ],
};

export function createBuiltinEvent(connector: ConnectorRecord): FrictionEvent {
  const options = TEMPLATE_LIBRARY[connector.id] ?? TEMPLATE_LIBRARY["builtin-slack"];
  const template = options[Math.floor(Math.random() * options.length)];
  const receivedAt = nowIso();
  const base: FrictionEvent = {
    id: createId("evt"),
    sourceId: connector.id,
    sourceType: connector.sourceType,
    receivedAt,
    status: "queued",
    trace: [
      createTraceEntry("captured", `Captured from ${connector.name}`, connector.snapshot),
    ],
    evaluation: {} as FrictionEvent["evaluation"],
    ...template,
  };

  base.evaluation = evaluateEvent(base);
  base.trace.push(
    createTraceEntry(
      "classified",
      base.evaluation.headline,
      base.evaluation.recommendation,
      base.evaluation.lane === "intervention" ? "warning" : base.evaluation.lane === "green" ? "positive" : "neutral"
    )
  );

  return base;
}
